---
- name: Convert Wall Point to Switch Port
  hosts: localhost
  gather_facts: no
  vars_files:
    - wall_point_mapping.yml
    - switch_mapping.yml
    - switch_ip_mapping.yml
  
  tasks:
    - name: Convert wall point to switch port
      set_fact:
        port_number: "{{ wall_point_mapping[wall_point] }}"
      when: wall_point is defined
      
    - name: Fail if wall point not found
      fail:
        msg: "Wall point {{ wall_point }} not found in mapping"
      when: port_number is not defined

    - name: Find Switch for Given Room
      set_fact:
        switch_name: "{{ item.key }}"
      loop: "{{ switch_mapping | dict2items }}"
      when: room is defined and room in item.value

    - name: Set device type based on room and wall point
      set_fact:
        device_type: "{{ device_mapping[room][wall_point] }}"
      when: room is defined and wall_point is defined and device_mapping is defined
